name: ml-kata
channels:
  - defaults
  - pytorch
  - huggingface
  - conda-forge
dependencies:
  - python=3.10.12
  - numpy=1.23.5
  - pip=23.1.2
  - tqdm=4.66.1
  - pytorch=2.1.0
  - black=22.6.0
  - datasets=2.15.0
  - tokenizers=0.13.3
  - transformers=4.32.1
  - evaluate
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - ipykernel=6.15.0
  - ipywidgets=7.7.1
  - wandb=0.12.2