name: ml-kata
channels:
  - defaults
  - pytorch
  - huggingface
  - conda-forge
dependencies:
  - python=3.7.13
  - numpy=1.21.6
  - pip=21.1.3
  - tqdm=4.64.1
  - pytorch=1.11.0
  - black=22.6.0
  - datasets=2.1.0
  - tokenizers=0.12.1
  - transformers=4.20.1
  - evaluate
  - scikit-learn=1.0.2
  - matplotlib=3.5.3
  - ipykernel=6.15.0
  - ipywidgets=7.7.1
  - wandb=0.12.21
